spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: expense_tracker_test
      collection:
        transaction: transactions_test
        event: events_test

server:
  port: 8082

logging:
  level:
    com.example.expense_tracker: INFO
    org.springframework.data.mongodb: INFO 