spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      collection-name: ${MONGODB_COLLECTION_NAME}

server:
  port: ${SERVER_PORT}

logging:
  level:
    com.example.expense_tracker: INFO
    org.springframework.data.mongodb: INFO 