spring:
  application:
    name: expense-tracker
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/familyHub

server:
  port: ${SERVER_PORT}

logging:
  level:
    root: INFO
    com.example.expense_tracker: ${LOG_LEVEL}
    org.springframework.data.mongodb: ${MONGODB_LOG_LEVEL} 

# Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always 