spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: expense_tracker_dev
      collection:
        transaction: transactions_dev
        event: events_dev

server:
  port: 8081

logging:
  level:
    com.example.expense_tracker: DEBUG
    org.springframework.data.mongodb: DEBUG 